<?php

// function webform_elected_opennorth_represent_install() {
//   drupal_install_schema('webform_elected_opennorth_representatives');
// }
// 
// function webform_elected_opennorth_represent_uninstall() {
//   drupal_uninstall_schema('webform_elected_opennorth_representatives');
// }

/**
* Implementation of hook_schema().
*/
function webform_elected_opennorth_represent_schema() {
  $schema['webform_elected_opennorth_representatives'] = array(
    'fields' => array(
      'representative_set' => array('type' => 'varchar', 'not null' => TRUE, 'length' => 64),
      'email' => array('type' => 'varchar', 'not null' => TRUE, 'length' => 64),
      'resource' => array('type' => 'text', 'not null' => TRUE),
    ),
    'primary key' => array('representative_set', 'email'),
  );
  return $schema;
}
